### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by ber4444** [sisyphsu/dateparser#6]
We get a crash on Android 6 and 7 devices (LG and Samsung so far):

```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/ZoneId;
       at com.github.sisyphsu.dateparser.DateBuilder.<clinit>(DateBuilder.java:21)
       at com.github.sisyphsu.dateparser.DateParser.<init>(DateParser.java:23)
       at com.github.sisyphsu.dateparser.DateParserBuilder.build(DateParserBuilder.java:207)
       at com.github.sisyphsu.dateparser.DateParserUtils.<clinit>(DateParserUtils.java:20)
       at com.github.sisyphsu.dateparser.DateParserUtils.parseDate(DateParserUtils.java:29)
```

https://developer.android.com/reference/java/time/ZoneId is Android 8+ only so your library doesn't support older OS versions.

**Comment by sisyphsu** [comment]
Yes, it uses lots of `java.time.*`, so it only works in JDK 1.8+, don't support old versions.

**Comment by ber4444** [comment]
Java 8 is not a problem, but yes the `java.time.*` APIs are not available, see https://jakewharton.com/androids-java-8-support/

I guess you could have a ThreeTenBP version as a fallback for Android 6 and 7. Or if not, just warn SDK consumers of limitations.

**Comment by sisyphsu** [comment]
I'm considering use `joda-time` to replace `java.time`, `joda` is more compatible with older versions.

**Comment by ber4444** [comment]
Actually, the `joda-time` GH page says `Joda-time is no longer in active development except to keep timezone data up to date. [...] Projects needing to support lower API levels can use the ThreeTenABP library.` and the ThreeTenABP GH page says `Development on this library is winding down. Please consider switching to Android Gradle plugin 4.0, java.time.*, and its core library desugaring feature in the coming months.` I was using the Android Gradle plugin 3.6.2 so should try it with the pre-release 4.0 plugin. When I look at https://developer.android.com/studio/preview/features#j8-desugar, I can see only `A subset of java.time` is supported so let's see if that is enough.

**Comment by ber4444** [comment]
That worked, closing it.

**Comment by yogurtearl** [comment]
for future reference, java8 desugaring link:
https://developer.android.com/studio/releases/gradle-plugin#j8-library-desugaring
